version: '3.8'

# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-sgs-admin:
    build:
      context: .
      target: development
    depends_on:
      - redis
    image: ffc-sgs-admin-development
    environment:
      NODE_ENV: development
    ports:
      - "3800:3800"
      - "9256:9229"
    volumes:
      - ./app/:/home/node/app/
      - ./package.json:/home/node/package.json
  ffc-sgs-admin-postgres:
    ports:
      - "5434:5432"

  redis:
    image: redis:4.0.14
    volumes:
      - redis_data:/data
    ports:
      - "6390:6379"

volumes:
  redis_data:
