{{- include "ffc-helm-library.container-config-map" (list . "ffc-sgs-admin.config-map") -}}
{{- define "ffc-sgs-admin.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}  
  REDIS_HOSTNAME: {{ .Values.container.redisHostname | quote }}
  REDIS_PORT: {{ .Values.container.redisPort | quote }}
  REDIS_PARTITION: {{ .Values.container.redisPartition | quote }}
  SESSION_CACHE_TTL: {{ .Values.container.sessionCacheTTL | quote }}  
  LOGIN_REQUIRED: {{ .Values.container.loginRequired | quote }}
  SERVICE_BUS_HOST: {{ .Values.container.messageQueueHost | quote }}
  PROJECT_DETAILS_QUEUE_ADDRESS: {{ .Values.container.projectDetailsQueueAddress | quote }}
  CONTACT_DETAILS_QUEUE_ADDRESS: {{ .Values.container.contactDetailsQueueAddress | quote }}
  APPLICATION_RECEIVED_SUBSCRIPTION_ADDRESS: {{ .Values.container.applicationSubscriptionAddress | quote }}
  APPLICATION_DETAIL_TOPIC_ADDRESS: {{ .Values.container.applicationDetailTopicAddress | quote }}
  BACKEND_POLLING_HOST: {{ .Values.container.backendPollingHost | quote }}
  POLLING_INTERVAL: {{ .Values.container.pollingInterval | quote }}
  POLLING_RETRIES: {{ .Values.container.pollingRetries | quote }}
  APPINSIGHTS_CLOUDROLE: {{ .Values.name }}
  GOOGLE_TAG_MANAGER_KEY: {{ .Values.container.googleTagManagerKey | quote }}
  GOOGLE_TAG_MANAGER_SERVER_KEY: {{ .Values.container.googleTagManagerServerKey | quote }}
  START_PAGE_URL: {{ .Values.container.startPageUrl | quote }}
  SURVEY_LINK: {{ .Values.container.surveyLink | quote }}
  POSTGRES_DB: {{ quote .Values.postgresService.postgresDb }}
  POSTGRES_HOST: {{ quote .Values.postgresService.postgresHost }}
  POSTGRES_PORT: {{ quote .Values.postgresService.postgresPort }}
  POSTGRES_SCHEMA_NAME: {{ quote .Values.postgresService.postgresSchema }}
  SHAREPOINT_HOSTNAME: {{ .Values.container.sharePointHostname | quote }}
  SHAREPOINT_SITE_PATH: {{ .Values.container.sharePointSitePath | quote }}
  SHAREPOINT_DOCUMENT_LIBRARY: {{ .Values.container.sharePointDocumentLibrary | quote }}
  SGS_NOTIFICATION_QUEUE_ADDRESS: {{ quote .Values.container.sgsNotificationQueueAddress }}
  SGS_SERVICE_BUS_HOST: {{ .Values.container.sgsMessageQueueHost | quote }}
{{- end -}}
