{{- include "ffc-helm-library.deployment" (list . "ffc-sgs-admin.deployment") -}}
{{- define "ffc-sgs-admin.deployment" -}}
spec:
  template:
    spec:
      containers:
      - {{ include "ffc-helm-library.container" (list . "ffc-sgs-admin.container") }}
{{- end -}}
